version: "3"
services:
  app:
    container_name: app
    build: 
        context: .
        dockerfile: kinder-setup/.docker/app.Dockerfile
    restart: always
    ports:
      - "80:3000"
    links:
      - db
  db:
    container_name: db
    build: 
        context: .
        dockerfile: kinder-setup/.docker/mongo.Dockerfile
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
